name: Continuous Deployment (CD)

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches: [ "main" ]

jobs:

  deploy:
    
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        node-version: [18.x]
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - run: npm ci
    
    - name: Install dependencies
      run: npm install

    - name: Deploy
      run: npm run deploy
      env:
        deployment_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}